name: Flutter Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'  # вкажи твою версію Flutter

    - name: Install dependencies
      run: flutter pub get

    - name: Generate localization
      run: flutter gen-l10n

    - name: Analyze project
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: moodmap-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
